FROM node:22-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@10.34.5 --activate

# Stage 1: Build the application
FROM base AS build
ENV NODE_ENV=development

ARG BACKEND_URL
ARG NUXT_PUBLIC_BASE_URL
ARG NUXT_PUBLIC_DM_WS_URL
ARG NUXT_PUBLIC_DM_SSE_URL
ARG NUXT_PUBLIC_RECAPTCHA_SITE_KEY
ARG NUXT_PUBLIC_GOOGLE_CLIENT_ID
ARG NUXT_PUBLIC_GOOGLE_REDIRECT_URI
ARG NUXT_PUBLIC_GOOGLE_SCOPE
ARG NUXT_PUBLIC_GITHUB_CLIENT_ID
ARG NUXT_PUBLIC_GITHUB_REDIRECT_URI
ARG NUXT_PUBLIC_GITHUB_SCOPE
ARG NUXT_PUBLIC_USE_MOCKS=false
ARG RAVEN_TENOR_KEY

ENV BACKEND_URL=$BACKEND_URL
ENV NUXT_PUBLIC_BASE_URL=$NUXT_PUBLIC_BASE_URL
ENV NUXT_PUBLIC_DM_WS_URL=$NUXT_PUBLIC_DM_WS_URL
ENV NUXT_PUBLIC_DM_SSE_URL=$NUXT_PUBLIC_DM_SSE_URL
ENV NUXT_PUBLIC_RECAPTCHA_SITE_KEY=$NUXT_PUBLIC_RECAPTCHA_SITE_KEY
ENV NUXT_PUBLIC_GOOGLE_CLIENT_ID=$NUXT_PUBLIC_GOOGLE_CLIENT_ID
ENV NUXT_PUBLIC_GOOGLE_REDIRECT_URI=$NUXT_PUBLIC_GOOGLE_REDIRECT_URI
ENV NUXT_PUBLIC_GOOGLE_SCOPE=$NUXT_PUBLIC_GOOGLE_SCOPE
ENV NUXT_PUBLIC_GITHUB_CLIENT_ID=$NUXT_PUBLIC_GITHUB_CLIENT_ID
ENV NUXT_PUBLIC_GITHUB_REDIRECT_URI=$NUXT_PUBLIC_GITHUB_REDIRECT_URI
ENV NUXT_PUBLIC_GITHUB_SCOPE=$NUXT_PUBLIC_GITHUB_SCOPE
ENV NUXT_PUBLIC_USE_MOCKS=$NUXT_PUBLIC_USE_MOCKS
ENV RAVEN_TENOR_KEY=$RAVEN_TENOR_KEY

# Install dependencies
COPY package.json pnpm-lock.yaml ./
RUN --mount=type=cache,id=pnpm-store,target=/pnpm/store \
    pnpm install --frozen-lockfile

# Copy the rest of the application code
COPY . .
RUN pnpm mock:gen

# change back to production for build
ENV NODE_ENV=production

# Increase memory limit for Node.js during build
ENV NODE_OPTIONS="--max-old-space-size=4096"

# Build Nuxt (SSR)
RUN pnpm build

# Stage 2: Runtime
FROM base

# Copy build output and necessary files
ENV NODE_ENV=production
COPY --from=build /app/.output /app/.output
COPY package.json ./

EXPOSE 3000
CMD ["pnpm", "start"]
